version: "2"
services:
  neo4j:
    image: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - $HOME/neo4j/data:/data
  redis:
    image: redis:alpine
    ports:
      - 6379:6379

